# Generated by Django 4.2.1 on 2023-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groups",
            old_name="teachers",
            new_name="teacher",
        ),
        migrations.RemoveField(
            model_name="students",
            name="groups",
        ),
        migrations.AddField(
            model_name="groups",
            name="students",
            field=models.ManyToManyField(to="groups.students"),
        ),
    ]
